### ISSUE TITLE
Please add BugSec 

### ISSUE THREAD

**Issue by Isreeal** [mluggy/techmap#11]
היי,
האם ניתן להוסיף את "באגסק" ?
ח.פ 513650812
כתובת - נים 2 ראשל"צ (קניון ראשונים, מגדל עסקים)
https://www.bugsec.com/
קטגוריה - Cybersecurity
תודה רבה.

**Comment by mluggy** [comment]
כדי לזרז את הבקשה ממליץ לספק שם, תיאור, תמונה (200 פיקסלים).

**Comment by mluggy** [comment]
Hi, please send a pull request (which now includes a built-in validator), or opt for an express (paid) service.
