### ISSUE TITLE
הכנסת חברת אינטנסיטי גלובל למאגר חברות על המפה

### ISSUE THREAD

**Issue by ShayIntensity** [mluggy/techmap#2]
היי,
אודה להוספת חברת INTENSITY GLOBAL למפה שיצרתם,
מיקום המטה: נתניה, רחוב פולג 5, המלאכה
אך למעשה עובדים ברימוט ויש לנו אתרים נוספים בכל הארץ מצפון לדרום.
אתר החברה: https://intensity-global.com/
לכל שאלה נוספת אני זמינה- מנהלת HR ואופרציה שי יהלום- 054-7760360

תודה!

**Comment by mluggy** [comment]
היי, שי. שלחי את מספר הח.פ וכל הכתובות (רחוב, מספר, עיר) ואכליל את כולם במפה.
אם יש תיאור או קטגוריה מתאימה מכאן https://github.com/mluggy/techmap/blob/main/categories.json זה יעזור.

**Comment by mluggy** [comment]
Hi, please send a pull request (which now includes a built-in validator), or opt for an express (paid) service.
