### ISSUE TITLE
https://maphub.net/mluggy doesn't work from mobile

### ISSUE THREAD

**Issue by rosti-il** [mluggy/techmap#23]
This is a very interesting and promising project but it works from a personal computer's browser only (I use Firefox and also tried Edge).
In case of web browser in a mobile platform it doesn't work at all.
Tried in both the Samsung web browser and the Google Chrome for Android 12.
Tried with IPv6+IPv4 (via WiFi) and with IPv4 only (mobile internet without WiFi)

Instead of opening multiple maps it redirects into https://maphub.net/lander and shows some domain parked web page, like in the following screenshots:

![Screenshot_20240812_175445_Chrome](https://github.com/user-attachments/assets/9e523600-5f0d-4169-90bd-5fd758d9a79d)

==============================================================================

![Screenshot_20240812_175547_Samsung Internet](https://github.com/user-attachments/assets/ea7834e3-a84f-41d9-820c-2ab914c35610)

**Comment by mluggy** [comment]
very weird, like the domain was wrongly typed or DNS-cached. try https://maphub.net/mluggy/techmap (main map) or https://maphub.net/mluggy (list of maps).

**Comment by rosti-il** [comment]
Opening both URLs has the same result as above. Could it be somehow related to UserAgent of mobile browsers? Does it work in your Android devices? Are you connected to Partner?

**Comment by rosti-il** [comment]
My mistake. In mobile I wrote the URL manually and used .com instead of .net because of the [.com] button and because I used to .com sites. This is false negative and could be closed. Sorry for my confusion.
