### ISSUE TITLE
Please add "Final"  to the companies list

### ISSUE THREAD

**Issue by omer-solaredge** [mluggy/techmap#24]
![SmartSelect_20240813_131830_Opera](https://github.com/user-attachments/assets/d44cfe9c-e579-4c91-bded-5cd9d17c06b9)

Description:
Since 2001, Final has taken a leading role in algorithmic trading, pioneering and championing High Frequency Trading based on math, physics, and advanced computer science.

Address: יד חרוצים 7 הרצליה

Website: Final.co.il

**Comment by mluggy** [comment]
It would be easier (and faster) if you locate its json file for final and push the updates there.

**Comment by omer-solaredge** [comment]
> Since 2001, Final has taken a leading role in algorithmic trading, pioneering and championing High Frequency Trading based on math, physics, and advanced computer science.

OK
I tried. Hope that I did it as I should do...

**Comment by mluggy** [comment]
closing as already submitted by @ayalash
