### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by akiva-skolnik** [mluggy/techmap#34]
I came across the following broken link: https://demo.tandoo.io/
I found that the link is listed in their LinkedIn, so it might be a good idea to check the link before adding it.
Also, their page say they operate from Tel Aviv, not Kedumim.

**Comment by mluggy** [comment]
Thanks. I rely on automation for enrichment and rasham havarot for addresses. that company specifically looks ceased but I'll wait for more data.

**Comment by mluggy** [comment]
note I had to re-save and push the files with utf-8 without BOM encoding.
