### ISSUE TITLE
חברות חסרות

### ISSUE THREAD

**Issue by ericabramov** [mluggy/techmap#4]
1. Yahoo Israel
https://www.yahooinc.com/careers/
https://maps.app.goo.gl/EgmZUcgs5JASV2No8

2. Meta/Facebook (איך זה לא קיים??)
3. Verint Israel (you put only Cognyte)
4. Edgio 
אין להם משרדים פיסיים חח
אבל יש פעילות בארץ
הנה משרה שנסגרה לא מזמן
 https://www.linkedin.com/jobs/view/3903329210

**Comment by mluggy** [comment]
תודה אריק --

1. הוספתי את יאהו (פולטרה עקב ״חיסול בעקבות מיזוג״)
2. הוספתי את פייסבוק (פולטרה עקב ״מפרה משנת 2021״)
3. הוספתי את verint (נשמטה אולי בגלל cognyte)

את edgio אפשר להוסיף אחרי שיתמקמו בארץ (כולל ח.פ).

השינויים כאן: https://github.com/mluggy/techmap/commit/2ca1da9491420fadf062731fbeadaabfc29b70b5
