### ISSUE TITLE
Add SeatGeek Israel

### ISSUE THREAD

**Issue by hananya-beck** [mluggy/techmap#5]
SeatGeek Israel
סיטגיק ישראל
Company number 512897620

כתובת:
אצל: הדולב 3 פארק הייטק ברלב

חברה אמריקאית עם סניף בישראל

עבודה מרחוק אפשרית בצורה מלאה 

ניתן לפנות אלי לפרטים נוספים

**Comment by mluggy** [comment]
added: https://maphub.net/mluggy/techmap
